sudo: required
services:
  - docker
before_install:
  - docker build -t wazzadevli0/react-test -f ./client-1/Dockerfile.dev ./client-1
script:
  - docker run -e CI=true wazzadevli0/react-test npm test -- --coverage

after_success:
  - dockerbuild -t wazzadevli0/multi-client ./client-1
  - dockerbuild -t wazzadevli0/multi-nginx ./nginx
  - dockerbuild -t wazzadevli0/multi-worker ./worker
  - dockerbuild -t wazzadevli0/multi-server ./server
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push wazzadevli0/multi-client
  - docker push wazzadevli0/multi-nginx
  - docker push wazzadevli0/multi-worker
  - docker push wazzadevli0/multi-server