sudo: required
services:
  - docker
before_install:
  - docker build -t wazzadevli0/react-test -f ./client-1/Dockerfile.dev ./client-1
script:
  - docker run -e CI=true wazzadevli0/react-test npm test -- --coverage

after_success:
  - docker build -t wazzadevli0/multi-client ./client-1
  - docker build -t wazzadevli0/multi-nginx ./nginx
  - docker build -t wazzadevli0/multi-worker ./worker
  - docker build -t wazzadevli0/multi-server ./server
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push wazzadevli0/multi-client
  - docker push wazzadevli0/multi-nginx
  - docker push wazzadevli0/multi-worker
  - docker push wazzadevli0/multi-server

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-west-2
  app: docker-udemy-multi-docker
  env: DockerUdemyMultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-036392005668
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

