version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  api:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile.dev   # only specifices the file name
      context: ./server            # context is where you specify the location
    volumes:
        - /app/node_modules   # Dont override the folder
        - ./server:/app       # link the volumes so looking in app you will be looking into local server folder.
    environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - PGUSER=postgres
        - PGHOST=postgres
        - PGPORT=5432
        - PGDATABASE=postgres
        - PGPASSWORD=postgres_password
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  ngnix:
    restart: always
    depends_on:
      - api
      - client
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
        - '3050:80'

